name:                chaosbox
version:             0.1.1.0
#synopsis:
#description:
homepage:            https://github.com/5outh/chaosbox#readme
license:             MIT
author:              Benjamin Kovach
maintainer:          bkovach13@gmail.com
copyright:           2018 Benjamin Kovach
category:            Art
extra-source-files:
- README.md

default-extensions:
  - TypeApplications
  - RecordWildCards
  - LambdaCase

dependencies:
  - base >= 4.7 && < 5
  - directory
  - cairo
  - colour
  - linear
  - MonadRandom
  - mtl
  - optparse-applicative
  - process
  - random
  - random-fu
  - random-source
  - semigroups
  - time
  - transformers
  - mersenne-random-pure64
  - vector
  - containers
  - array
  - rvar
  - semigroupoids
  - lens

library:
    source-dirs: src

executables:
  chaosbox-example:
    source-dirs: example
    main: Main.hs
    dependencies:
      - chaosbox
