name:                chaosbox
version:             0.0.0.0
synopsis: A Generative Art Framework
description: A Generative Art Framework
homepage:            https://github.com/5outh/chaosbox#readme
license:             MIT
author:              Benjamin Kovach
maintainer:          bkovach13@gmail.com
copyright:           2018 Benjamin Kovach
category:            Art
extra-source-files:
- README.md

ghc-options:
  - -Wall

default-extensions:
  - TypeApplications
  - RecordWildCards
  - LambdaCase
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - TypeFamilies
  - MultiParamTypeClasses
  - FlexibleContexts

dependencies:
  - base >= 4.7 && < 5
  - directory
  - cairo
  - colour
  - linear
  - MonadRandom
  - mtl
  - optparse-applicative
  - process
  - random
  - random-fu
  - random-source
  - semigroups
  - time
  - transformers
  - mersenne-random-pure64
  - vector
  - containers
  - array
  - rvar
  - semigroupoids
  - lens

library:
    source-dirs: src
    exposed-modules:
      - ChaosBox
      - ChaosBox.Affine
      - ChaosBox.Color
      - ChaosBox.Draw
      - ChaosBox.Generate
      - ChaosBox.Geometry
      - ChaosBox.Geometry.Angle
      - ChaosBox.Geometry.Arc
      - ChaosBox.Geometry.Circle
      - ChaosBox.Geometry.Class
      - ChaosBox.Geometry.ClosedCurve
      - ChaosBox.Geometry.Curve
      - ChaosBox.Geometry.Ellipse
      - ChaosBox.Geometry.Line
      - ChaosBox.Geometry.Path
      - ChaosBox.Geometry.Polygon
      - ChaosBox.Geometry.Quad
      - ChaosBox.Geometry.Rect
      - ChaosBox.Geometry.Triangle
      - ChaosBox.HasV2
      - ChaosBox.Math
      - ChaosBox.Math.Matrix
      - ChaosBox.Noise
      - ChaosBox.Pixel
      - ChaosBox.Random

executables:
  chaosbox-example:
    source-dirs: example
    main: Main.hs
    dependencies:
      - chaosbox
