name:                chaosbox
version:             0.0.0.1
synopsis: A Generative Art Framework
description: A Generative Art Framework
homepage:            https://github.com/5outh/chaosbox#readme
license:             MIT
author:              Benjamin Kovach
maintainer:          bkovach13@gmail.com
copyright:           2020 Benjamin Kovach
category:            Art
extra-source-files:
- README.md

ghc-options:
  - -Wall

default-extensions:
  - TypeApplications
  - RecordWildCards
  - LambdaCase
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - TypeFamilies
  - MultiParamTypeClasses
  - FlexibleContexts
  - FlexibleInstances
  - PatternSynonyms

dependencies:
  - base >= 4.7 && < 5
  - directory
  - colour
  - linear
  - MonadRandom
  - mtl
  - optparse-applicative
  - process
  - random
  - random-fu
  - random-source
  - semigroups
  - time
  - transformers
  - mersenne-random-pure64
  - vector
  - containers
  - array
  - rvar
  - semigroupoids
  - lens
  - sdl2
  - gi-cairo-render
  - conduit
  - monad-loops

library:
    source-dirs: src

executables:
  chaosbox-example:
    source-dirs: example
    main: Main.hs
    dependencies:
      - chaosbox
